/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CellEditor: typeof import('./src/components/cell/CellEditor.vue')['default']
    ColumnHeaderCell: typeof import('./src/components/cell/ColumnHeaderCell.vue')['default']
    EditableCell: typeof import('./src/components/cell/EditableCell.vue')['default']
    EditButtons: typeof import('./src/components/edit/EditButtons.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElProgress: typeof import('element-plus/es')['ElProgress']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSkeleton: typeof import('element-plus/es')['ElSkeleton']
    ElTableV2: typeof import('element-plus/es')['ElTableV2']
    FileButtons: typeof import('./src/components/file/FileButtons.vue')['default']
    RecentFilesSection: typeof import('./src/components/file/RecentFilesSection.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    RowNumberCell: typeof import('./src/components/cell/RowNumberCell.vue')['default']
    SearchBox: typeof import('./src/components/search/SearchBox.vue')['default']
    SearchPanel: typeof import('./src/components/search/SearchPanel.vue')['default']
    SheetButtons: typeof import('./src/components/sheet/SheetButtons.vue')['default']
    SheetSelector: typeof import('./src/components/sheet/SheetSelector.vue')['default']
    StatusBar: typeof import('./src/components/layout/StatusBar.vue')['default']
    TableEditor: typeof import('./src/components/TableEditor.vue')['default']
    Toolbar: typeof import('./src/components/layout/Toolbar.vue')['default']
    UpdateDialog: typeof import('./src/components/UpdateDialog.vue')['default']
  }
}
