/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CellEditor: typeof import('./src/components/CellEditor.vue')['default']
    ColumnHeaderCell: typeof import('./src/components/ColumnHeaderCell.vue')['default']
    EditableCell: typeof import('./src/components/EditableCell.vue')['default']
    EditButtons: typeof import('./src/components/EditButtons.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElTableV2: typeof import('element-plus/es')['ElTableV2']
    FileButtons: typeof import('./src/components/FileButtons.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    RowNumberCell: typeof import('./src/components/RowNumberCell.vue')['default']
    SearchBox: typeof import('./src/components/SearchBox.vue')['default']
    SearchPanel: typeof import('./src/components/SearchPanel.vue')['default']
    SheetButtons: typeof import('./src/components/SheetButtons.vue')['default']
    SheetSelector: typeof import('./src/components/SheetSelector.vue')['default']
    StatusBar: typeof import('./src/components/StatusBar.vue')['default']
    TableEditor: typeof import('./src/components/TableEditor.vue')['default']
    Toolbar: typeof import('./src/components/Toolbar.vue')['default']
  }
}
