import {
  DEFAULT_COLUMN_WIDTH_PX,
  DEFAULT_ROW_HEIGHT_PX,
  MAX_COLUMN_WIDTH_PX,
  MAX_ROW_HEIGHT_PX,
  MIN_INTERACTIVE_COLUMN_WIDTH_PX,
  MIN_INTERACTIVE_ROW_HEIGHT_PX,
} from '@/protocol/generatedEditorPolicy';

export const DEFAULT_GRID_COLUMN_WIDTH = DEFAULT_COLUMN_WIDTH_PX;
export const DEFAULT_GRID_ROW_HEIGHT = DEFAULT_ROW_HEIGHT_PX;
export const MIN_GRID_COLUMN_WIDTH = MIN_INTERACTIVE_COLUMN_WIDTH_PX;
export const MIN_GRID_ROW_HEIGHT = MIN_INTERACTIVE_ROW_HEIGHT_PX;
export const MAX_GRID_COLUMN_WIDTH = MAX_COLUMN_WIDTH_PX;
export const MAX_GRID_ROW_HEIGHT = MAX_ROW_HEIGHT_PX;
