import {
  MAX_CELL_TEXT_BYTES as GENERATED_MAX_CELL_TEXT_BYTES,
  MAX_MUTATION_TEXT_BYTES as GENERATED_MAX_MUTATION_TEXT_BYTES,
  MAX_SEARCH_QUERY_BYTES as GENERATED_MAX_SEARCH_QUERY_BYTES,
  MAX_SET_CELL_CHANGES as GENERATED_MAX_SET_CELL_CHANGES,
  MAX_DOCUMENT_RESPONSE_BYTES as GENERATED_MAX_DOCUMENT_RESPONSE_BYTES,
  MAX_SHEET_REGION_RESPONSE_BYTES as GENERATED_MAX_SHEET_REGION_RESPONSE_BYTES,
  SHEET_REGION_TILE_COLUMNS as GENERATED_SHEET_REGION_TILE_COLUMNS,
  SHEET_REGION_TILE_ROWS as GENERATED_SHEET_REGION_TILE_ROWS,
} from '@/types/protocol';
import {
  MAX_BATCH_TEXT_BYTES,
  MAX_CELL_CHANGES_PER_BATCH,
  MAX_CELL_TEXT_BYTES,
  MAX_DOCUMENT_WIRE_BYTES,
  MAX_REGION_RESPONSE_BYTES,
  MAX_SEARCH_QUERY_BYTES,
  SHEET_REGION_TILE_COLUMNS,
  SHEET_REGION_TILE_ROWS,
} from '@/resourcePolicy/editorResourcePolicy';

export * from '@/resourcePolicy/editorResourcePolicy';

export function assertEditorResourcePolicyCompatibility() {
  const mismatches = [
    ['MAX_DOCUMENT_RESPONSE_BYTES', MAX_DOCUMENT_WIRE_BYTES, GENERATED_MAX_DOCUMENT_RESPONSE_BYTES],
    ['MAX_SHEET_REGION_RESPONSE_BYTES', MAX_REGION_RESPONSE_BYTES, GENERATED_MAX_SHEET_REGION_RESPONSE_BYTES],
    ['MAX_SET_CELL_CHANGES', MAX_CELL_CHANGES_PER_BATCH, GENERATED_MAX_SET_CELL_CHANGES],
    ['MAX_CELL_TEXT_BYTES', MAX_CELL_TEXT_BYTES, GENERATED_MAX_CELL_TEXT_BYTES],
    ['MAX_MUTATION_TEXT_BYTES', MAX_BATCH_TEXT_BYTES, GENERATED_MAX_MUTATION_TEXT_BYTES],
    ['MAX_SEARCH_QUERY_BYTES', MAX_SEARCH_QUERY_BYTES, GENERATED_MAX_SEARCH_QUERY_BYTES],
    ['SHEET_REGION_TILE_ROWS', SHEET_REGION_TILE_ROWS, GENERATED_SHEET_REGION_TILE_ROWS],
    ['SHEET_REGION_TILE_COLUMNS', SHEET_REGION_TILE_COLUMNS, GENERATED_SHEET_REGION_TILE_COLUMNS],
  ].filter(([, runtime, generated]) => runtime !== generated);
  if (mismatches.length > 0) {
    throw new Error(
      `Frontend editor resource policy is incompatible with the generated protocol: ${mismatches
        .map(([name, runtime, generated]) => `${name}=${runtime}/${generated}`)
        .join(', ')}`,
    );
  }
}
