import {
  MAX_CELL_TEXT_BYTES,
  MAX_MUTATION_TEXT_BYTES,
  MAX_SEARCH_QUERY_BYTES,
  MAX_SET_CELL_CHANGES,
  MAX_DOCUMENT_RESPONSE_BYTES,
  MAX_SHEET_REGION_RESPONSE_BYTES,
  SHEET_REGION_TILE_COLUMNS,
  SHEET_REGION_TILE_ROWS,
} from '@/protocol/generatedEditorPolicy';

export const MAX_DOCUMENT_WIRE_BYTES = MAX_DOCUMENT_RESPONSE_BYTES;
export const MAX_REGION_RESPONSE_BYTES = MAX_SHEET_REGION_RESPONSE_BYTES;
export const MAX_CELL_CHANGES_PER_BATCH = MAX_SET_CELL_CHANGES;
export const MAX_BATCH_TEXT_BYTES = MAX_MUTATION_TEXT_BYTES;

export {
  MAX_CELL_TEXT_BYTES,
  MAX_SEARCH_QUERY_BYTES,
  SHEET_REGION_TILE_COLUMNS,
  SHEET_REGION_TILE_ROWS,
};
