import { MAX_SHEET_REGION_RESPONSE_BYTES } from '@/types/protocol';

export const MAX_RESIDENT_REGION_BYTES = MAX_SHEET_REGION_RESPONSE_BYTES;
export const MAX_REGION_RESPONSE_BYTES = MAX_SHEET_REGION_RESPONSE_BYTES;
